# Env based parameters are set
instance_name: ansible-demo-dev
lc_name: ansible-demo-launch-config
asg_name: ansible-demo-asg
region: us-east-1
keypair: ec2-one
image_id: ami-4b133c5d
type: t2.nano
subnet_id: subnet-7c40ce57
instance_role: arn:aws:iam::355380910796:instance-profile/wp-s3-read
security_groups:
    - sg-eb36639a
    - sg-dc095cad
asg_subnet_id:
    - subnet-7c40ce57
    - subnet-8b0142fc
asg_az:
    - us-east-1a
    - us-east-1b
